version: '3.8'

services:
  back-assembleia.cloud.local:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    depends_on:
      - network.postgres.cloud.local
    networks:
      - ms-network
  network.postgres.cloud.local:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATA_BASE_NAME}
      POSTGRES_USER: ${POSTGRES_DATA_BASE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DATA_BASE_PASS}
      TZ: "America/Brasilia"
    networks:
      - ms-network
  pg-admin.cloud.local:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL:  ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    ports:
      - "16549:80"
    depends_on:
      - network.postgres.cloud.local
    networks:
      - ms-network
networks:
  ms-network:
    driver: bridge