spring:
  r2dbc:
    url: r2dbc:postgresql://network.postgres.cloud.local:5432/db-assembleia?schema=public
    username: user-assembleia
    password: pass-assembleia
  main:
    allow-bean-definition-overriding: true

liquibase:
  url: jdbc:postgresql://network.postgres.cloud.local:5432/db-assembleia?schema=public

master-config:
 full-url: r2dbc:postgresql://${spring.r2dbc.username}:${spring.r2dbc.password}@network.postgres.cloud.local:5432/db-assembleia?schema=public

management:
  endpoint:
    health:
      show-details: always